project:
  type: website

website:
  title: "ISSS624 Geospatial Analytics"
  sidebar:
    style: "floating"
    search: true
    contents:
      - contents: index.qmd
        section: Home
      - section: "Hands on Ex"
        contents: 
          - href: "Handson_Ex/Handson_Ex01/Handson_Ex01.qmd"
          - href: "Handson_Ex/Handson_Ex02/Handson_Ex02.qmd"
          - href: "Handson_Ex/Handson_Ex03/Handson_Ex03.qmd"
          - href: "Handson_Ex/Handson_Ex04/Handson_Ex04.qmd"
          - href: "Handson_Ex/Handson_Ex05/Handson_Ex05.qmd"
      - section: "In class Ex"
        contents: 
          - href: "Inclass_Ex/Inclass_Ex01/Inclass_Ex01.qmd"
          - href: "Inclass_Ex/Inclass_Ex02/Inclass_Ex02.qmd"
          - href: "Inclass_Ex/Inclass_Ex03/Inclass_Ex03.qmd"
      - section: "Take Home Ex"
        contents: 
          - href: "Takehome_Ex/Takehome_Ex01/Takehome_Ex01.qmd"
          - href: "Takehome_Ex/Takehome_Ex02/Takehome_Ex02.qmd"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

